//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CudaCLA.rc
//
#define IDD_CUDACLA_DIALOG              102
#define IDD_ABTDLG                      103
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define ID_TOOLS_INDEXUNITYFINGERPRINTASREFERENCELIBRARY 32771
#define ID_SPARSEARRAY_INDEXASCANDIDATELIBRARY 32772
#define ID_SPARSEARRAY_                 32773
#define ID_SPARSEARRAY_LOADREFERENCELIBRARY 32774
#define ID_SPARSEARRAY_LOADCANDIDATELIBRARY 32775
#define ID_SPARSEARRAY_COMPAREDATABASE  32776
#define ID_COMPRESSEDFINGERPRINT_INDEXASREFERENCELIBRARY 32777
#define ID_COMPRESSEDFINGERPRINT_INDEXASCANDIDATELIBRARY 32778
#define ID_COMPRESSEDFINGERPRINT_LOADREFERENCELIBRARY 32779
#define ID_COMPRESSEDFINGERPRINT_LOADCANDIDATELIBRARY 32780
#define ID_COMPRESSEDFINGERPRINT_COMPAREDATABASE 32781
#define ID_OPTION_SHOWSTATUS            32782
#define ID_OPTION_SHOWHISTOGRAM         32783
#define ID_OPTION_EXPORT                32784
#define ID_OPTION_ABOUT                 32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
